import { useState } from "react";
import { LeadCard } from "@/components/LeadCard";
import { LeadDetail } from "@/components/LeadDetail";
import "../styles/index.css";

// Mock data
const LEADS = [
  {
    id: "1",
    name: "Karl Connon",
    company: "Gong.io",
    title: "Vice President of Sales - EMEA",
    avatar: "https://media.licdn.com/dms/image/v2/D560BAQEginaUF2_5cg/company-logo_200_200/company-logo_200_200/0/1689291197848/gong_io_logo?e=1745452800&v=beta&t=EHYvHlm0MHd_rdRu6olDEQ2UIrKriThLNswln677Aq4",
    activity: "Connected with Apollo sales team",
    location: "London, England",
    employeeCount: "1001-5000",
    industry: "Information Services",
    description: "Corsearch intelligent Trademark & Brand Protection solutions are revolutionizing how companies commercialize and protect their most valuable assets. Trusted by thousands of brands worldwide."
  },
  {
    id: "2",
    name: "Ben Moyer",
    company: "OpenAI",
    title: "RevOps",
    avatar: "https://media.licdn.com/dms/image/v2/C4E0BAQG0lRhNgYJCXw/company-logo_200_200/company-logo_200_200/0/1678382029963/openai_logo?e=1745452800&v=beta&t=aBPmHM9z-uuBEo3LgoJqT6UEqm9VUvACucmwj7EeHfs",
    activity: "Reviewed competitor on G2",
    location: "San Francisco, CA",
    employeeCount: "51-200",
    industry: "Security Software",
    description: "Modern authentication & fraud prevention platform."
  },
];

const Index = () => {
  const [selectedLead, setSelectedLead] = useState(LEADS[0]);

  return (
    <div className="app-container">
      <header className="header">
        <div className="tabs">
          <button className="tab active">Overview</button>
          <button className="tab">Duo leads</button>
          <button className="tab">Alpha</button>
        </div>
      </header>
      
      <div className="main-content">
        <div className="leads-sidebar">
          <div className="sidebar-header">
            <h2 className="sidebar-title">Good morning, John!</h2>
            <p className="sidebar-subtitle">
              Here you can find a curated list of recommended leads generated by Duo
            </p>
            
            <div className="leads-list">
              {LEADS.map((lead) => (
                <LeadCard
                  key={lead.id}
                  lead={lead}
                  isActive={selectedLead?.id === lead.id}
                  onClick={() => setSelectedLead(lead)}
                />
              ))}
            </div>
          </div>
        </div>
        
        <div className="detail-section">
          <LeadDetail lead={selectedLead} />
        </div>
      </div>
    </div>
  );
};

export default Index;