import { useState } from "react";
import { LeadCard } from "@/components/LeadCard";
import { LeadDetail } from "@/components/LeadDetail";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

// Mock data
const LEADS = [
  {
    id: "1",
    name: "Karl Connon",
    company: "Corsearch",
    title: "Vice President of Sales - EMEA",
    avatar: "/placeholder.svg",
    activity: "Connected with Apollo sales team",
    location: "London, England",
    employeeCount: "1001-5000",
    industry: "Information Services",
    description: "Corsearch intelligent Trademark & Brand Protection solutions are revolutionizing how companies commercialize and protect their most valuable assets. Trusted by thousands of brands worldwide."
  },
  {
    id: "2",
    name: "Ben Moyer",
    company: "Stytch",
    title: "RevOps",
    avatar: "/placeholder.svg",
    activity: "Reviewed competitor on G2",
    location: "San Francisco, CA",
    employeeCount: "51-200",
    industry: "Security Software",
    description: "Modern authentication & fraud prevention platform."
  },
];

const Index = () => {
  const [selectedLead, setSelectedLead] = useState(LEADS[0]);

  return (
    <div className="min-h-screen bg-background">
      <div className="h-16 border-b px-6 flex items-center bg-secondary/30">
        <Tabs defaultValue="overview" className="w-full">
          <TabsList className="bg-transparent border-0">
            <TabsTrigger value="overview" className="data-[state=active]:bg-white data-[state=active]:shadow-none">Overview</TabsTrigger>
            <TabsTrigger value="duo-leads" className="data-[state=active]:bg-white data-[state=active]:shadow-none">Duo leads</TabsTrigger>
            <TabsTrigger value="alpha" className="data-[state=active]:bg-white data-[state=active]:shadow-none">Alpha</TabsTrigger>
          </TabsList>
        </Tabs>
      </div>
      
      <div className="flex h-[calc(100vh-4rem)]">
        <div className="w-[400px] border-r overflow-y-auto">
          <div className="p-6">
            <h2 className="text-2xl font-semibold mb-1">Good morning, John!</h2>
            <p className="text-base text-muted-foreground mb-6">
              Here you can find a curated list of recommended leads generated by Duo
            </p>
            
            <div className="space-y-3">
              {LEADS.map((lead) => (
                <LeadCard
                  key={lead.id}
                  lead={lead}
                  isActive={selectedLead?.id === lead.id}
                  onClick={() => setSelectedLead(lead)}
                />
              ))}
            </div>
          </div>
        </div>
        
        <div className="flex-1 overflow-y-auto">
          <LeadDetail lead={selectedLead} />
        </div>
      </div>
    </div>
  );
};

export default Index;